export const ASSETS = {
  icons: {
    arrowLeft: '/assets/arrow-left.svg',
    arrowRight: '/assets/arrow-right.svg',
    chevronDown: '/assets/chevron-down.svg',
    eye: '/assets/eye.svg',
    eyeOff: '/assets/eye-off.svg',
    logOut: '/assets/log-out.svg',
    mail: '/assets/mail.svg',
    mailGray: '/assets/mailGray.svg',
    mapPin: '/assets/map-pin.svg',
    menu: '/assets/menu.svg',
    menuOpen: '/assets/menu_open.svg',
    minus: '/assets/minus.svg',
    minusMobile: '/assets/minus-mobile.svg',
    phone: '/assets/phone.svg',
    plus: '/assets/plus.svg',
    plusMobile: '/assets/plus-mobile.svg',
    shoppingBag: '/assets/shopping-bag.svg',
    socialGoogle: '/assets/Social-icon-google.svg',
    whatsapp: '/assets/whatsapp.svg',
    facebook: '/assets/facebook.svg',
    instagram: '/assets/instagram.svg',
    x: '/assets/x.svg',
    alertCircle: '/assets/alert-circle.svg',
    check: '/assets/check.svg',
    uploadCloud: '/assets/upload-cloud.svg',
    trash2: '/assets/trash-2.svg',
    loader: '/assets/loader.svg',
    model3d: '/assets/deployed_code_update.svg',
  },

  illustrations: {
    katauroLogo: '/assets/Katauro.svg',
    ideasConLuz: '/assets/Ideas_con_luz.svg',
    artboard11: '/assets/Artboard_11.svg',
  },

  content: {
    catImage: '/assets/cat_image.png',
    catImage1: '/assets/cat_image1.png',
    catImage2: '/assets/cat_image2.png',
    catImage3: '/assets/cat_image3.png',
    imagePlaceholder: '/assets/Image.png',
    team: '/assets/team.png',
    techo: '/assets/techo.png',
    pared: '/assets/pared.png',
    mesa: '/assets/mesa.png',
    lampara: '/assets/lampara.png',
    featured1: '/assets/featured1.png',
    featured2: '/assets/featured2.png',
    backImage: '/assets/back_image.webp',
    backImage2: '/assets/back_image2.png',
    backImage3: '/assets/back_image3.png',
    backImage4: '/assets/back_image4.png',
    backImage5: '/assets/back_image5.png',
    carouselImage: '/assets/Carousel_image.png',
    carouselImage2: '/assets/Carousel_image2.png',
    loginImage: '/assets/loginImage.png',
    pie: '/assets/pie.png',
  },

  cloudinary: {
    loginSideImage: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778362599/loginImage_skcii7.png',
    teamHero: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1775019483/equipo-katauro.jpg_xug0xt.jpg',
    carouselArtboard1: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1775273492/Artboard_1.jpg_wccoph.jpg',
    carouselArtboard2: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1775273493/Artboard_2.jpg_wt6ieb.jpg',
    carouselArtboard3: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1775273493/Artboard_3.jpg_tmeilp.jpg',

    categoryMesa: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1779934612/mesa_te0bud.jpg',
    categoryPared: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1779934612/pared_wmupvl.jpg',
    categoryPie: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1779934612/pie_iw5gb6.jpg',
    categoryTecho: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1779934613/techo_gvwuzk.jpg',

    teamMembers: {
      angelFornaris: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533230/16-Angel_R._Fornaris-_Director_General.jpg_gnxhit.jpg',
      rosaRodriguez: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533229/15-Rosa_Y._Rodriguez_Adan-_Directora_Adjunta.jpg_fultpj.jpg',
      gabrielaGarcia: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533229/14-Gabriela_Garcia_Valdespino-_Dependienta.jpg_stbcaf.jpg',
      adisYilian: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533229/12-Adis_Yilian_Bravo_Frion_Yilian_-_Especialista_en_Compras.jpg_nyebwl.jpg',
      giselleRuiz: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533228/13-Giselle_de_la_Caridad_Ruiz_Fernandez_de_Velasco-_Dependienta.jpg_xlvy5w.jpg',
      davidBatista: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533225/8-David_Batista_Reyes-_Jefe_de_Brigada_de_Carpinteria_y_Herreria.jpg_a5oqjt.jpg',
      giselleRosell: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533225/11-Giselle_Rosell_Alonso-_Administradora_General.jpg_ogjouv.jpg',
      porfirioMerino: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533225/10-Porfirio_Merino_Figueredo_Merino_-_Jefe_de_Brigada_de_Pantalla.jpg_fomncs.jpg',
      marioMartin: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533223/9-Mario_Martin_Duenas_Aralla-_Operario_de_Herreria.jpg_yusemh.jpg',
      alejandroTorres: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533222/7-Alejandro_Torres_Caballero-_Jefe_de_Produccion.jpg_zcbyyk.jpg',
      adrianFonseca: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533221/3-Adrian_Fonseca_Maceda-_Especialista_en_Herreria.jpg_buf1lh.jpg',
      juanFernando: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533218/2-Juan_Fernando_Infante_Duran_El_Profe_-_Asesor_de_Diseno.jpg_flhrwj.jpg',
      lourdesSoto: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533219/4-Lourdes_Soto_Bengochea-_Operaria_en_Patalla.jpg_ukqll5.jpg',
      andresEmilio: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533220/5-Andres_Emilio_Zabala_Rivas_El_tio_-_Operario_en_Acabado.jpg_jgnmzs.jpg',
      yoandyNolazco: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533219/6-Yoandy_Nolazco_Cala-_Especialista_en_Acabado.jpg_pdymbz.jpg',
      joseLazaro: 'https://res.cloudinary.com/dmhadvchw/image/upload/v1778533218/1-Jose_Lazaro_Aballi_Rabasa_El_Chino_-_Especialista_en_Mantenimiento.jpg_k8cpcz.jpg',
    },
  },
} as const;
